### ISSUE TITLE
Forces magnitude

### ISSUE THREAD

**Issue by antonagafonov** [facebookresearch/plush_dataset#4]
Hi guys,
Kudos on your great work,
In the VEO paper, the optimization problem is set as the total object's Energy minimization, where one of the terms in total object's Energy is the **Virtual Work** of the external forces. As I see in the files, there is force direction tracking using aruco_ids. How do you determine the force magnitude in your setup?

Another question is also regarding points which are connected to wires, as I see in **baby_alien** **verts_fixed** is indeed in ears hands, and legs ending areas. For legs I believe the contact indeed is spread to a lot of points, but what about ears and hands, the wires are connected to a small number of points, but there are hundreds of points defined at each wire connection. Can you please explain why there are much more points defined connected to a wire? I suspect is for optimization stability.

Thanks a lot,
AA

![image](https://user-images.githubusercontent.com/63194980/187624673-915364ad-ec1d-41f7-bae8-fb809d56883f.png)

**Comment by hsiaoyu** [comment]
Hi! I include a new file "plush_data.pdf" that contains an estimation for the relation between the force and the distance that we are using. I would like to point out that since we didn't take gravity into consideration, the learned stiffness(material parameters) is proportional to external force, meaning that only the ratio between the stiffness and the external force is important but not the absolute value. As for the fixed points, unfortunately, we can only estimate those manually. Like you said, fixing too few points may lead to numerical instability during simulation, since the point cloud is down-sampled to 1/10 of points for simulation.

**Comment by antonagafonov** [comment]
Got You,
Thanks
